function probabilityTable = pokerHandStatsTable()
%POKERHANDSTATS Returns a table of the likelihood of getting every kind of
%poker hand

data = { ...
    "RoyalFlush", 4; ...
    "StraightFlush", 36; ...
    "FourOfAKind", 624; ...
    "FullHouse", 3744; ...
    "Flush", 5108; ...
    "Straight", 10200; ...
    "ThreeOfAKind", 54912; ...
    "TwoPair", 123552; ...
    "Pair", 1098240; ...
    "Single", 1302540};

totalNumberOfPossibleHands = nchoosek(52,5);

handTypes = vertcat(data{:,1});
numHands = vertcat(data{:,2});
probabilities = numHands/totalNumberOfPossibleHands;

probabilityTable = table( ...
    handTypes, probabilities, numHands, ...
    VariableNames = ["HandType","Probability","NumberOfHandsPossible"]);

end

